const SIGNIN = {
    SIGNIN_LOAD: 'SIGNIN_LOAD',
    SIGNIN_LOAD_SUCCESS: 'SIGNIN_LOAD_SUCCESS',
    SIGNIN_LOAD_FAIL: 'SIGNIN_LOAD_FAIL'
}

const SIGNUP = {
    SIGNUP_LOAD: 'SIGNUP_LOAD',
    SIGNUP_LOAD_SUCCESS: 'SIGNUP_LOAD_SUCCESS',
    SIGNUP_LOAD_FAIL: 'SIGNUP_LOAD_FAIL'
}

const CREATEPOST = {
    CREATEPOST_LOAD: 'CREATEPOST_LOAD',
    CREATEPOST_LOAD_SUCCESS: 'CREATEPOST_LOAD_SUCCESS',
    CREATEPOST_LOAD_FAIL: 'CREATEPOST_LOAD_FAIL'
}
const SOCIAL = {
    SOCIAL_LOAD: 'SOCIAL_LOAD',
    SOCIAL_LOAD_SUCCESS: 'SOCIAL_LOAD_SUCCESS',
    SOCIAL_LOAD_FAIL: 'SOCIAL_LOAD_FAIL'
}
const MYPOSTS = {
    MYPOSTS_LOAD: 'MYPOSTS_LOAD',
    MYPOSTS_LOAD_SUCCESS: 'MYPOSTS_LOAD_SUCCESS',
    MYPOSTS_LOAD_FAIL: 'MYPOSTS_LOAD_FAIL'
}

const MYFOLLOWER = {
    MYFOLLOWER_LOAD: 'MYFOLLOWER_LOAD',
    MYFOLLOWER_LOAD_SUCCESS: 'MYFOLLOWER_LOAD_SUCCESS',
    MYFOLLOWER_LOAD_FAIL: 'MYFOLLOWER_LOAD_FAIL'
}

const MYFOLLOWINGPOSTS = {
    MYFOLLOWINGPOSTS_LOAD: 'MYFOLLOWINGPOSTS_LOAD',
    MYFOLLOWINGPOSTS_LOAD_SUCCESS: 'MYFOLLOWINGPOSTS_LOAD_SUCCESS',
    MYFOLLOWINGPOSTS_LOAD_FAIL: 'MYFOLLOWINGPOSTS_LOAD_FAIL'
}

const SEARCH_USER = {
        SEARCH_USER_LOAD: 'SEARCH_USER_LOAD',
        SEARCH_USER_LOAD_SUCCESS: 'SEARCH_USER_LOAD_SUCCESS',
        SEARCH_USER_LOAD_FAIL: 'SEARCH_USER_LOAD_FAIL'
}

const POST_ID = {
    POST_ID_LOAD: 'POST_ID_LOAD',
    POST_ID_SUCCESS: 'POST_ID_SUCCESS',
    POST_ID_FAIL: 'POST_ID_FAIL'
}

export { SIGNIN,SIGNUP,CREATEPOST,SOCIAL,MYPOSTS,MYFOLLOWER,MYFOLLOWINGPOSTS,SEARCH_USER,POST_ID }